name: Docker Image Build

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/**'
      - 'docker-compose.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: docker build -t privatebin:dev ./docker/privatebin
