name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deployment script via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/privatebin|| git clone https://github.com/MohammadHuseyn/privatebin-devops.git /home/${{ secrets.SERVER_USER }}/privatebin
            cd /home/${{ secrets.SERVER_USER }}/privatebin
            git reset --hard HEAD
            git pull origin main
            docker build -t privatebin:dev ./docker/privatebin
            docker stop privatebin-dev || true
            docker rm privatebin-dev || true
            docker run -d -p 80:80 --name privatebin-dev privatebin:dev
